### ISSUE TITLE
Self destroying bot-messages

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/kcd-discord-bot-v1#16]
Random thought I was just having;

The bots currently post messages like the one below in `#🤖-talk-to-bots`

> HI! I deleted a message you just posted because it's a duplicate of this one:... . Please give it time for users to respond to your first post.

I don't have the numbers, but I'm not sure if this makes sense to most users, and if they all understand what's going on, or even read the message in `#🤖-talk-to-bots`

Would it make sense to let the bot reply in the channel itself, and remove the message after a certain timeout (60 seconds?)?

That way, the user sees the bot message in the current active channel, but the channels history won't be stuffed with bot messages.

**Comment by kentcdodds** [comment]
I like this idea. How about this:

The bot needs to talk to someone (respond to their `?help` request or something like this), then they send the message in `#🤖-talk-to-bots` mentioning the user and *also* send a message to the originating channel also mentioning the user saying `"Hey <user>, could you please check <link-to-message>?"` which would self-destruct after 20 seconds.

There are quite a lot of things where this would be useful and help redirect people to the bots channel rather than sending bot messages in the wrong channels.

Thoughts?

**Comment by kentcdodds** [comment]
Of course if they send the message in the bots channel this would not be needed.

**Comment by smeijer** [comment]
That sounds good to me. Sending a message like `Hey <user>, could you please check <link-to-message>?` might indeed be better, as it is more compact (creating less noise in the main channel). And that way the real bot message persists, for the cases where the user posts a message, and directly navigates away.

**Comment by kentcdodds** [comment]
Ok, we now have a utility for this and several commands have shifted to self-destroying messages. It can sometimes be tricky to know when to use this feature and we can adjust over time.

Here's one example: https://github.com/kentcdodds/kcd-discord-bot/blob/2c85a550aac331cb6ca1addbe4d8b356d229aadc/src/commands/command-fns/info.js#L76

That'll send a self-destroying message as well as a message in the talk to bots channel.
