### ISSUE TITLE
Implement recurring streams

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/kcd-discord-bot-v1#47]
Some folks want to have a regularly scheduled stream. Here's what I'm thinking:

```
?schedule-stream "Office Hours with Jane" every Wednesday from 3:00 PM - 3:45 PM IST
```

This would result in the following message being put into the upcoming streams channel:

```
📣 Every Wednesday from 3:00 PM - 8:00 PM UTC @jane will be live streaming "Office Hours with Jane". React with ✋ to be notified when the time arrives.
```

Then, the cleanup would work basically the same, except it would identify the message as a recurring event and not delete the message.

The recurring thing might be tricky if we want to support more than weekly (monthly, 2nd and 4th Thursdays, etc. etc.), but maybe there's a library to help with that as well?

Thoughts?

**Comment by marcosvega91** [comment]
this is an interesting idea 🎸 , I thought that `chono` did that because when you parse a data it will return an array but they did not implement this feature, see https://github.com/wanasit/chrono/issues/349. We could parse the string using both `chrono` and an our parser, or we should find another library that do this. In the issue a guy suggests this library https://www.npmjs.com/package/parse-messy-schedule

**Comment by kentcdodds** [comment]
That messy-schedule thing looks promising!

**Comment by Aprillion** [comment]
If there are more candidate libraries, I would vote for one that can recover from parse errors the most gracefully.

https://github.com/substack/parse-messy-schedule/blob/master/test/next.js looks promising, but I don't see negative tests of invalid inputs there :/


E.g. for `?schedule-stream "Office Hours with Jane" wendesdays from 3:00 - 3:45` I would expect one of following:

a) fail with a generic message
b) fail with parse error quoting the first problematic word
c) fail because of missing timezone
d) magically recover from the typo and schedule something in some timezone (let the streamer delete it if wrong)

**Comment by kentcdodds** [comment]
I'd prefer to not guess/magically recover and try to give them as useful an error message as possible.

**Comment by kentcdodds** [comment]
Ok, so this one's proved to be pretty difficult. Turns out finding a natural language parser for recurring schedules that works reliably is tricky.

But I realized a problem: What if you need to cancel a single meetup? You could just ignore it, but then everyone would get a notification only to find out it was canceled which would be annoying. You could delete the schedule message and re-recreate it later, but then you'd lose all the `✋` reactions and people would have to do it over again.

So what if instead of having meetups which are started automatically by the bot, we say you *must* always explicitly start the meetup. This way if you decide to cancel or you're late or something, you just do nothing and nothing happens.

So here's what I'm thinking:

```
?meetup schedule recurring Office Hours with Jane on Wednesdays from 3:00pm - 4:00pm Mountain Time
```

This would create the following message in a `#⏱-scheduled-meetups` channel:

```
📣 @jane has scheduled a recurring meetup: Office Hours with Jane on Wednesdays from 3:00pm - 4:00pm Mountain Time. React with ✋ to be notified when it starts.
```

This would also create the following message in `#🤖-talk-to-bots`:

```
@jane, I've added your recurring meetup to #⏱-scheduled-meetups` <link>. When you're ready to start, simply react to the message with 🏁 and I'll notify your followers and those who have opted-into being notified that it's started.
```

So when the host starts a meetup by reacting to the message with `🏁`, the bot will delete the message if it's not recurring or simply remove the reaction if it is recurring, it'll create a voice channel if the meetup doesn't have a zoom link, then it will notify folks that the meetup has started in `#🏁-meetup-starting`.

I think this is the simplest solution that is also the most functional. I welcome thoughts on this idea and feedback.

**Comment by balavishnuvj** [comment]
yup this works, only concern is the message in `#🤖-talk-to-bots` might be hard to find over time. We would need to this message to start the stream, right? or do we react to the message in `#⏱-scheduled-meetups`  with `🏁` to start the stream?

**Comment by kentcdodds** [comment]
> or do we react to the message in #⏱-scheduled-meetups with 🏁 to start the stream?

Yes, you react to the message in the scheduled meetups channel. There should only be a handful of messages in there and it's the same message people are subscribing to so I think that should make sense.

**Comment by kentcdodds** [comment]
This is implemented! 🎉
